### ISSUE TITLE
"XboxKeyboardMouse has stopped working"

### ISSUE THREAD

**Issue by mouldyXD** [fqlx/XboxKeyboardMouse#1]
I have installed SCPToolkit however everytime i launch the program it crashes, any tips?

**Comment by fqlx** [comment]
Any errors?  Does it say Off or Waiting?

**Comment by mouldyXD** [comment]
It says off for about 4 seconds and then it crashes

**Comment by fqlx** [comment]
Do you know what version of Direct X you have?
And if you have a controller plugged in (as player 1), unplug it.  Let me know if that fixes it.

**Comment by mouldyXD** [comment]
12 and i have no controllers plugged in, i do have the 360 wireless dongle plugged in though.

**Comment by mouldyXD** [comment]
Unplugging the dongle doesn't fix it.

**Comment by fqlx** [comment]
I'll update the app to provide a stack trace or we can collab over remote desktop.  Remote desktop would be faster right now if you have visual studio installed and want to help out.
