### ISSUE TITLE
smoothness issue 

### ISSUE THREAD

**Issue by diablo2002** [fqlx/XboxKeyboardMouse#100]
Hi , i tried this method on many games and i figure out that this way is not smooth at all specially with some games like rainbow six siege i tried a lot of deadzones and nothing can anyone help please

**Comment by DavidRieman** [comment]
Can you add details?  Try going to Settings, loading a preset (default?), Settings tab, enable Show the Mouse Cursor, save all changes, go to your game, calibrate the dead zone, and try moving the mouse one pixel on screen - does the game react by making a small aim change?

**Comment by DavidRieman** [comment]
I figured out the main problem with the dead zone calcs.  Code incoming.

**Comment by DavidRieman** [comment]
Let us know if you have any issues with the new installer / deadzone aiming.  Closing issue.

**Comment by MatheuzinGameprays** [comment]
DavidRieman, I was using it and I need some helps.  I don't know if the SPC can change anything on the mouse. I'm saying that because idk if u did something more than i know with the mouse better performace at the flicks or thing like that. If i can do someting to better that tell me pleaaseeee.

**Comment by diablo2002** [comment]
DavidRieman , sorry for being late but it still struggles and it doesn't feel like a playable first person shooter game with kb/ms
