### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by diablo2002** [fqlx/XboxKeyboardMouse#108]
When the new update with new deadzone will came out ?

**Comment by airsquared** [comment]
It's already out. Just download it.

**Comment by diablo2002** [comment]
DavidRieman said that he will improve the original deadzone but the source code is not yet updated

**Comment by DavidRieman** [comment]
Well the _code_ is available at https://github.com/DavidRieman/XboxKeyboardMouse (master branch).  But I am hoping the others will respond soon WRT releasing via the ClickOnce installer.

**Comment by DavidRieman** [comment]
Ok, the new version is available!
Per the git homepage it is available at: https://cdn.rawgit.com/fqlx/XboxKeyboardMouse/master/Installer/setup.exe

**Comment by DavidRieman** [comment]
Let us know if you have any issues with the new installer / deadzone aiming.  Closing issue.
