### ISSUE TITLE
Can´t install via setup.exe

### ISSUE THREAD

**Issue by MLengl** [fqlx/XboxKeyboardMouse#111]
The following error is occuring all the time when I hit installer:

> An error occurred trying to download 'https://raw.githubusercontent.com/fqxl/XboxKeyboardMouse/master/Installer/XboxKeyboardMouse.application'.

I can start the application directly and it´s status is green, but the xbox app doesn´t recognize mouse/keyboard as controller.

This let me think about:
Do I need to plug in a real one and then it´s going to work or is it a full emulator?

**Comment by DavidRieman** [comment]
There was a problem with the installer, which has now been updated.  I typo'd in the installer path.  You might need to manually install again via https://cdn.rawgit.com/fqlx/XboxKeyboardMouse/master/Installer/setup.exe

**Comment by DavidRieman** [comment]
Let us know if you have any issues with the fixed installer.  Closing issue.

**Comment by obviator** [comment]
I'm getting this issue now with the installer you linked to. I have access the .application file directly no problem. Install.log attached
[install.log](https://github.com/fqlx/XboxKeyboardMouse/files/3255932/install.log)

**Comment by DavidRieman** [comment]
@obviator can you try again with the [installation instructions](https://github.com/fqlx/XboxKeyboardMouse#installation) link instead?  A new version was deployed yesterday so worth a fresh try and fresh log if broken.  Thanks.

**Comment by obviator** [comment]
I'm afraid it's the same. Thanks for the fast response!

```
An error occurred trying to download 'https://raw.githubusercontent.com/fqlx/XboxKeyboardMouse/master/Installer/XboxKeyboardMouse.application'.

See the setup log file located at 'C:\Users\tom\AppData\Local\Temp\VSD1A82.tmp\install.log' for more information.

```

[install.log](https://github.com/fqlx/XboxKeyboardMouse/files/3276152/install.log)

**Comment by DavidRieman** [comment]
I found a forum post with someone else running into the same issue with another click-once app: https://social.msdn.microsoft.com/Forums/en-US/ee125fc0-ddcb-43aa-a94a-e9c88d6afdce/urldownloadtocachefile-failed-with-hresult-2146697208?forum=winformssetup

The .application file is configured as an https request in our click-once configuration, and the file is served via https, so I don't think there's anything we can change with the installer; github isn't redirecting between http/https in this case.  So you might need to try the other work-around mentioned in the link, with changing settings.  Hope it works out for you!
