### ISSUE TITLE
Opens and then closes a few moments later

### ISSUE THREAD

**Issue by mishman36** [fqlx/XboxKeyboardMouse#116]
When i open the program, i have the Xbox app also open but the emulator still closes a few seconds after opening.

Please help

**Comment by airsquared** [comment]
This worked for me earlier:

1. Uninstall everything installed by this application(slimdx, any other libraries installed)
2. Unplug any physical Xbox peripherals
3. Open device manager and use "Uninstall Device" on all of the listed "Xbox 360 Peripherals"
4. Run ScpDriverInstaller.exe and uninstall
5. Delete the XboxKeyboardMouse folder
6. Reboot
7. Install [SlimDX (x86)](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/slimdx/SlimDX%20Runtime%20.NET%204.0%20x86%20(January%202012).msi) (this is a direct link to the download)
8. Download and run the [installer](https://cdn.rawgit.com/fqlx/XboxKeyboardMouse/master/Installer/setup.exe).

**Comment by mishman36** [comment]
Thanks alot it worked
