### ISSUE TITLE
Input lag

### ISSUE THREAD

**Issue by iZehnny** [fqlx/XboxKeyboardMouse#117]
Takes seconds to register my movements, can this be lowered by an better internet connection?

**Comment by DavidRieman** [comment]
_Seconds_?  Are you trying to control an Xbox One that is not in the same building / not on the same switch/router?  Try using a physical Xbox 360 controller attached to the same PC, without XboxKeyboardMouse running.  Do you have the same experience?

**Comment by airsquared** [comment]
Try running the Xbox streaming test from the app.

**Comment by DavidRieman** [comment]
If you still have trouble, feel free to reopen with further details.  Thanks.
