### ISSUE TITLE
Application says waiting

### ISSUE THREAD

**Issue by yokid** [fqlx/XboxKeyboardMouse#12]
Whenever I start it, it just says "waiting" in green, although the keyboard works fine in game, but the mouse doesn't work

**Comment by CallumCarmicheal** [comment]
Yokid, does this issue still persist on the new version?

**Comment by yokid** [comment]
No it works fine now Thank you

**Comment by CallumCarmicheal** [comment]
Aah okay, maybe just a temporary issue okay. Mind closing the issue :)

**Comment by yokid** [comment]
Will do
