### ISSUE TITLE
Instant Crashes

### ISSUE THREAD

**Issue by MoltenWifi** [fqlx/XboxKeyboardMouse#121]
Every time I open the application it crashes. When I open it again after the first crash it doesnt even show the UI. Please help as I want to use this for pubg on xbox one.

**Comment by Herbie74** [comment]
did you install the SlimDX x86  version?

**Comment by airsquared** [comment]
Try the troubleshooting instructions at #116.

**Comment by DavidRieman** [comment]
Let us know if you still have troubles with the click-once install version.
