### ISSUE TITLE
Mouse is inconsistent

### ISSUE THREAD

**Issue by fffstift223** [fqlx/XboxKeyboardMouse#126]
If I move the mouse slowly in cod iw, I dont do anything in-game. But when I move it fast it goes very fast. Its like I have a very low sensitivity with very high mouse acceleration. What settings do I use to improve this?

**Comment by diablo2002** [comment]
Try the F11/F12 process , and it will work

**Comment by RenanBan** [comment]
F12/F11 is the deadzone, press F12 and wait for the aim to move, when it does press it again to adjust the deadzone, F11 is a finer adjustment

**Comment by xboxkeyboardmouse** [comment]
On fortnite this does not work it still does not work after callibrating

**Comment by DavidRieman** [comment]
The calibration suggestion is solid.  There's another thread or two raising issues with Fortnite, so I'm closing this one.
