### ISSUE TITLE
low FPS?

### ISSUE THREAD

**Issue by redline99cs** [fqlx/XboxKeyboardMouse#127]
When using XboxKeyboardMouse i seem to be getting stuttering and low fps.
I tried with 4g which helped the lag but the movements are always erratic / robotic and seems low fps. 
As soon as i connect real xbox one controller the gameplay gets fluid again.
I tried modifying mouse setttings (modifier, sensitivity) but it didnt change much.
Also i seem to have less hiccups (sound stutter) when streaming on 4g then on fiber optics 5ghz internet which is kinda weird.

**Comment by redline99cs** [comment]
Its especially noticeable in Halo 5, the stutter is really bad.
Other games like Division run fine.

**Comment by xboxkeyboardmouse** [comment]
Not a problem for me. Only problem is mouse movements are not realistic, but are choppy and inconsitent

**Comment by DavidRieman** [comment]
I have not noticed any FPS difference in the Xbox app between using a real controller or a simulated controller.  Closing issue for now.  Let us know if there is still a clear reproducible problem though.
