### ISSUE TITLE
app crashes after 2 seconds of opening

### ISSUE THREAD

**Issue by CRYPTOSIMS** [fqlx/XboxKeyboardMouse#129]
i have reset my computer to fresh start. then downloaded both x86 and x64 slimdx. then installed xboxkeyboardmouse from the direct install link. also i have downloaded the driver for scp. any ideas? im on windows 10

**Comment by airsquared** [comment]
It will not work if you have the x64 slimdx, it must be x86.

**Comment by DavidRieman** [comment]
Using #138 to cover improving the SlimDX situation here.  Also, let us know if these tips did not resolve your issues.  Closing for now.
