### ISSUE TITLE
Driver installation / uninstallation failed: DriverPackageInstall failed with DIFxAPI error 0x000003EE

### ISSUE THREAD

**Issue by alek7777** [fqlx/XboxKeyboardMouse#130]
![error](https://user-images.githubusercontent.com/42330124/44010346-d45e016e-9e7f-11e8-82fc-a3d9c332b795.PNG)

**Comment by CircuitLord** [comment]
I'm having the same issue with a slightly different scenario. It randomly started happening before having been working fine and I can't figure out what in the world is causing it.

**Comment by DavidRieman** [comment]
There are some driver troubleshooting tips at #76 - Feel free to re-open if your issue is not resolved.  Thanks!
