### ISSUE TITLE
CHOPPY/INCONSISTENT MOUSE SENSITIVITY

### ISSUE THREAD

**Issue by xboxkeyboardmouse** [fqlx/XboxKeyboardMouse#135]
I play fortnite using this program I have tried out all of the combos for sensitivity and deadzone, raw input+sensitivity etc. But I never get that realistic mouse feel. Any settings anyone can tell me to help? By the way while callibrating the aim drifts to the top right corner of the screen it is not horizontal. And small movements do not move the aim and when you move the mouse fast the sensitivity reacts so sharply it moves very fast. All in all, aiming is a problem on fortnite because you cant build or aim weapons precisely. Anyone have ideal settings or have any tips? Program developers can you help? Let's try to revive this program to give people a free way to get a mouse and keyboard on Xbox without having to buy an adapter! Thanks for all the help you can give me.

**Comment by jaime628** [comment]
i have the exactly same issue, UP

**Comment by DavidRieman** [comment]
Closing as dupe for https://github.com/fqlx/XboxKeyboardMouse/issues/125.  Yes we'll have to investigate.
