### ISSUE TITLE
Mouse Moviments

### ISSUE THREAD

**Issue by jaime628** [fqlx/XboxKeyboardMouse#136]
Hello,

Congratz, everything works great but, i can't configure my mouse sensitive, even with F11/F22 its impossible to find a good one, someone can help me ? i think they should create a a video explain that and show us a perfect gameplay.

**Comment by xboxkeyboardmouse** [comment]
Hey yes, I have tried playing fortnite but it does not work no matter what. Try playing with deadzone its a bit better with 1000 sensitivity for Y AND X

**Comment by RenanBan** [comment]
You say fortnite, dont use the max sensitivity in game, work between the ingame sensitivity and the app Deadzone f11/f12. I'm currently playing with 0,7 X and Y, ADS is about 0.6, and if works fine for me. Its just a matter of you sitting down a couple of hours adjusting to your like. some games are trash to adjust like PUBG, the sensitivity there sucks so much

**Comment by DavidRieman** [comment]
Fortnite issues covered at https://github.com/fqlx/XboxKeyboardMouse/issues/125.
Created https://github.com/fqlx/XboxKeyboardMouse/issues/151 to track creating such videos.
Closing this issue.

**Comment by shrek88** [comment]
'Corsair m65 PRO RGB. (pollingrate 1000hz / 1 msec, "pointer speed50%") anyway.
my DPI is at 6800. in icue  x and y.snaping point middle or low p
how do get the correct tuning to that?. 
my now used setting to above stated is tickrate 1.
X:3400.00000000
Y:3400.00000000
Final modifier 1.00000000
yes no what tochange?
