### ISSUE TITLE
Slimdx site down?

### ISSUE THREAD

**Issue by poptartcrust** [fqlx/XboxKeyboardMouse#144]
There's no other way I can find to get the runtime

**Comment by RenanBan** [comment]
Man, I don't have the installer in my Downloads folder anymore, but in the folder of the Slim dx there is 3 installers of him that should work, send me your email and I'll sent it to you

**Comment by RenanBan** [comment]
SlimDX Runtime .NET 2.0 (January 2012)
SlimDX Runtime .NET 4.0 x64 (January 2012)
SlimDX Runtime .NET 4.0 x86 (January 2012)
I guess they'll solve your problem

**Comment by airsquared** [comment]
[Here](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/slimdx/SlimDX Runtime .NET 4.0 x86 (January 2012).msi) is a direct link to the download. I used the Internet Archive to get the link(it should be permanent).
