### ISSUE TITLE
Scptoolkit driver installed over mouse driver. Please help

### ISSUE THREAD

**Issue by kdemarcus** [fqlx/XboxKeyboardMouse#147]
Im new at computers and watched another source install the program and drivers wrong. I found the fourm after it was to late. I have uninstalled the mouse drivers and factory reset but for some reson it still say scptoolkit compatible device for manufacturer in the mouse properties. I have looked up everything i know to do, please help.

**Comment by kdemarcus** [comment]
Problem fixed. Had to buy a new mouse, i guess it went out idk.

**Comment by DavidRieman** [comment]
That sounds weird.  Glad you solved it.  Going to close this for now.
