### ISSUE TITLE
help please help

### ISSUE THREAD

**Issue by shrek88** [fqlx/XboxKeyboardMouse#159]
someone who know what they are doing since latest update on xboxapp to xbox console companion. it wont work. i managed to get it working(partly) by yea idont really know been trying diffrent solutions for the last 25+hours. (it will not activate (and mouse will not "stick"/attach in window probably cuz its standing in "standby(blue)" could someone fix this please. @fqlx @CallumCarmicheal @DavidRieman @stevemkroll @matthewmistele @airsquared

**Comment by secretspy911** [comment]
See issue [#158](https://github.com/fqlx/XboxKeyboardMouse/issues/158).

**Comment by DavidRieman** [comment]
Closing since you have worked around this, and the full solution will be tackled with 158.

**Comment by fqlx** [comment]
I'd would like if we could support any application name if there's a name change and it would allow us to support other apps like the PlayStation stream.  We could probably delete the check for the Xbox title and that would work.

**Comment by airsquared** [comment]
I think it would be better to allow the user to choose which app it checks for from the UI.
