### ISSUE TITLE
Mouse movement not being captured

### ISSUE THREAD

**Issue by Narusakaa** [fqlx/XboxKeyboardMouse#164]
I have recently tried to install XboxKeyboardMouse. Have got everything else working but it won't capture mouse movement, the cursor is still visible and isn't locked to the xbox app. Any help would be greatly appreciated.

**Comment by scxrlettz1** [comment]
I'm having the same problem

**Comment by Narusakaa** [comment]
Not sure how but I managed to get it working. I tried using the SCPToolkit to attempt to fix the issue but that made things worse by overriding my mouse drivers, so I reset windows (fresh Install) and that fixed the mouse problem but it also rolled back the xbox app? it's called xbox again instead of xbox console companion. Maybe the name is the problem I don't know. Hopefully it's an easy fix for those having the issue. wish I knew what I actually did to get it working to give tips.

**Comment by scxrlettz1** [comment]
I also managed to resolve it, I changed the name to microsoft visual studio 2019, the xbox stream file code, after that it created a file with the same name as xkm, but .snl. after that I executed and created a cmd tab and the normal application

**Comment by scxrlettz1** [comment]
sorry for my english, i'm brazilian and i using the translater

**Comment by DavidRieman** [comment]
It is that the installer only works with the "Xbox" app name.  The XKM code has been fixed to work with the new names but is not deployed yet.  Closing to consolidate this issue to #158.

**Comment by TheNumba1** [comment]
I'm not exactly sure if its what fixed mine, but I did a few things so try them all: I change my mouse tick rate to 9, I changed both sensitivities to 14200, I use dead zoning default with a 500 final modifier, and what I think TRULY FIXED IT was: go into the xboxkeyboardmouse master file, click downloads, profiles, choose your custom, not the default, and under mouse settings, change the deadzone to 6000, also open game before app then use windows button in stream to open app, u can disable cursor in the xboxkeyboard settings too
