### ISSUE TITLE
Mouse movement Error

### ISSUE THREAD

**Issue by KevKeb** [fqlx/XboxKeyboardMouse#173]
I tryed to uninstalled/reinstalled everything and to cange the mouse-settings but it dose not react on any mouse movement. The mouse keys works just fine. i tryed it on Rainbow six siege. no Error-code or something like that. Hope someone can help.
(Edit.1) Fallout 4 don´t work either.
(Edit.2) I need to unplug the controller from the xbox and conect it to the PC not sure if this is intended and the mouse deadzone calibration does not work. 
(Edit.3) The mouse dose not centers in the midle of the screen
(Edit.4) it seem like that is dose not lock on the Xbox app because of the name (it stays blue/dose not turn green)
(Edit.5) Canged the SlimDX Runtime to the 64x Bit version now it crashes after about 2 seconds

Version: -v1.1.0.5

Sorry for any grammar mistakes im german

**Comment by DavidRieman** [comment]
I believe you'll need to go back to the x86 version of Slim DX.

What is the exact title of the "Xbox Console Companion" window?  My first guess is the XboxApp is localized for you with a string we aren't comparing correctly, and we failed to detect it.

**Comment by KevKeb** [comment]
On the german version the Name is "Xbox Konsole-Begleiter"

**Comment by KevKeb** [comment]
@DavidRieman is there any known time when the app will be updated

**Comment by TheNumba1** [comment]
I'm not exactly sure if its what fixed mine, but I did a few things so try them all: I change my mouse tick rate to 9, I changed both sensitivities to 14200, I use dead zoning default with a 500 final modifier, and what I think TRULY FIXED IT was: go into the xboxkeyboardmouse master file, click downloads, profiles, choose your custom, not the default, and under mouse settings, change the deadzone to 6000  also oen game before app then use windows button
