### ISSUE TITLE
mouse not moving accurate  

### ISSUE THREAD

**Issue by atx343** [fqlx/XboxKeyboardMouse#19]
mouse not moving accurate  
Everything else works well

**Comment by CallumCarmicheal** [comment]
* I written a very very long explanation to why it doesn't work and how hard it is to do (For me atleast) but chrome crashed so I lost the will to live.

TLDR version: It is very hard and I can't find or figure out a effective way of doing it.

If you want to take a crack at it, it would be majorly appreciated: [Mouse Code](https://github.com/fqlx/XboxKeyboardMouse/blob/master/XboxKeyboardMouse/XboxController/Emulation/TranslateMouse.cs#L39)

**Comment by atx343** [comment]
there is a PC software for XIM4 & cronusmax adapter 
You may take a look
Possible will help to get to know the solution

**Comment by atx343** [comment]
i keep trying and trying changing the settings in game and mouse sensitivity but don't work

**Comment by atx343** [comment]
https://s29.postimg.org/gakwbpafb/Untitled.jpg
this setting works 4 me better than the default 
anyway Thx it is a great work i hope i can see the Full Version

**Comment by CallumCarmicheal** [comment]
I will be taking a look into this issue right now and try to make a better method of translating Mouse to Joy movement.

**Comment by atx343** [comment]
Thx i think we need more mouse settings..  When i move mouse slowly .... It doesn't move in game 
 I think every game needs specific settings 
http://m.imgur.com/0j7ues2?r

**Comment by CallumCarmicheal** [comment]
I'll take a look at it when I get home, I won't be in for most of the day so I'll take a re-evaluation and attempt to remake it from scratch, I will also be remaking the Options GUI so it is easier to use.

**Comment by atx343** [comment]
thx . I really appreciate your efforts

**Comment by CallumCarmicheal** [comment]
@atx343 I've started on making the new GUI because why not, might aswell!

![newgui](https://cloud.githubusercontent.com/assets/6545688/23098438/29e04b9a-f645-11e6-9424-5c6ffaa079b6.PNG)

**Comment by CallumCarmicheal** [comment]
I have found working settings that make the mouse smooth, you will have to modify and tinker with the sensitivity values but as far I can tell 1000x sensitivity works for me. I have a configurable DPI mouse and its set to low, the results may vary but as from what i can tell:

`
[Mouse]
Y_Sensitivity=1000.21299982071
TickRate=16
Is_RightStick=false
X_Inverted=false
X_Sensitivity=1000.21299982071
Final_Modifier=100
Y_Inverted=false
Type=3
`

Works for me, also note you can now set the mouse to the left stick. Read more on this in the info tab!

**Comment by xboxkeyboardmouse** [comment]
This does not work for me the small movements are still very choppy and do not go through. Even after the new deadzone update it does not feel smooth even while calibrated.How can I change my mouse dpi for that
