### ISSUE TITLE
SCP Bus failed to initialize

### ISSUE THREAD

**Issue by holygreal** [fqlx/XboxKeyboardMouse#2]
The program itself says "off"
Another window says "SCP Bus failed to initialize, then i press OK, and it says:

System.IO.IOException: SCP Virtual Bus Device not found
   at ScpDriverInterface.ScpBus..ctor(Int32 instance)
   at ScpDriverInterface.ScpBus..ctor()
   at XboxKeyboardMouse.Activate.CreateController()

Then i press OK, and the programs stops responding

**Comment by fqlx** [comment]
Is SCP driver installed?

**Comment by holygreal** [comment]
I believe it is. Is there anything other than the regular installation of SCPToolKit that I have to do?

**Comment by fqlx** [comment]
My guess is that you installed SCP Toolkit and didn't run the driver installer.  Try search for "ScpToolkit Driver Installer" and install the Windows service.

**Comment by holygreal** [comment]
Whoops, when I went to do that, it gave me an error because i never unchecked the Dualshock and Bluetooth drivers, and I didn't see the windows driver. That stopped the virtual bus error, but now i'm having the same problem as the other Issue where the program says "off" and then it says "XboxKeyboardMouse has stopped working"

**Comment by fqlx** [comment]
Install the SlimDX runtime.  I forgot to add that in the directions before and updated it.  https://slimdx.org/download.php
