### ISSUE TITLE
help with build.bat plz

### ISSUE THREAD

**Issue by TechnoDaft** [fqlx/XboxKeyboardMouse#26]
"Building Solution for 32 Bit (x86)...
msbuild "XboxKeyboardMouse.sln" /p:Configuration=Release /p:Platform="x86" /t:Build /p:OutputPath="C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\Downloads"
Microsoft (R) Build Engine Version 3.5.30729.8763
[Microsoft .NET Framework, Version 2.0.50727.8745]
Copyright (C) Microsoft Corporation 2007. All rights reserved.

Build started 2/23/2017 11:06:25 PM.
Project "C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse.sln" on node 0 (Build target(s)).
  Building solution configuration "Release|x86".
C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse\XboxKeyboardMouse.csproj : error MSB4132: The tools version "14.0" is unrecognized.
Done Building Project "C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse.sln" (Build target(s)) -- FAILED.

Build FAILED.

"C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse.sln" (Build target) (1) ->
(Build target) -> 
  C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse\XboxKeyboardMouse.csproj : error MSB4132: The tools version "14.0" is unrecognized.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.86
Deleting debug files
Renaming file to XboxKeyboardMouse 02 02 2017 - x86.exe
move /y "C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\Downloads\XboxKeyboardMouse.exe" "C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\Downloads\XboxKeyboardMouse 02 02 2017 - x86.exe"
 
 
Building Solution for 64 Bit (x86_64)...
msbuild "XboxKeyboardMouse.sln" /p:Configuration=Release /p:Platform="x64" /t:Build /p:OutputPath="C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\Downloads"
Microsoft (R) Build Engine Version 3.5.30729.8763
[Microsoft .NET Framework, Version 2.0.50727.8745]
Copyright (C) Microsoft Corporation 2007. All rights reserved.

Build started 2/23/2017 11:06:26 PM.
Project "C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse.sln" on node 0 (Build target(s)).
  Building solution configuration "Release|x64".
C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse\XboxKeyboardMouse.csproj : error MSB4132: The tools version "14.0" is unrecognized.
Done Building Project "C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse.sln" (Build target(s)) -- FAILED.

Build FAILED.

"C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse.sln" (Build target) (1) ->
(Build target) -> 
  C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\XboxKeyboardMouse\XboxKeyboardMouse.csproj : error MSB4132: The tools version "14.0" is unrecognized.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.40
Renaming file to XboxKeyboardMouse 02 02 2017 - x86_64.exe
move /y "C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\Downloads\XboxKeyboardMouse.exe" "C:\Users\Techn\OneDrive\Documents\XboxKeyboardMouse\Downloads\XboxKeyboardMouse 02 02 2017 - x86_64.exe"
Deleting un-needed files

Finished building (Check for any errors!)"

> Can someone please tell me how to fix the "error MSB4132: The tools version 14.0 is unrecognized." and "setdd not recognized as internal/external command"

**Comment by fqlx** [comment]
v14.0 toolset is in Visual Studio 2015.
Try installing that or don't even use the .bat file.

**Comment by TechnoDaft** [comment]
I've been trying to avoid putting in VS since I wiped my pc last month waiting for VS17 in March Is there a redistribution for it i can get for now or can you update the exe's to the newest?

**Comment by fqlx** [comment]
I don't have VS installed either lol

**Comment by TechnoDaft** [comment]
Well damn seen the new image and thought that looked alot nicer then the xmas version and wanted to try it. 

Well thanks anyways I'll try it next month when VS17 is released

**Comment by CallumCarmicheal** [comment]
@TechnoDaft I'll be rebuilding the applications tonight with a new graphical user interface I think you would like more. I will also be testing with earlier versions of Visual Studio and trying to fix your issue. As for me I won't be in my house for the next 7 hours~. I'll respond with my findings to hopefully fix your issue.

**Comment by CallumCarmicheal** [comment]
@TechnoDaft I have uploaded the new builds, as for your issue i cant tell what version of VS you have installed so i am unable to fix that issue for you although you can look at changing the VS Version in [XboxKeyboardMouse.sln](https://github.com/fqlx/XboxKeyboardMouse/blob/master/XboxKeyboardMouse.sln) and [XboxKeyboardMouse.csproj] (https://github.com/fqlx/XboxKeyboardMouse/blob/master/XboxKeyboardMouse/XboxKeyboardMouse.csproj)

**Comment by TechnoDaft** [comment]
alright thank you as for VS none at this time i wont be having VS till march 7th
