### ISSUE TITLE
Additional Dependencies Required

### ISSUE THREAD

**Issue by Otnehs** [fqlx/XboxKeyboardMouse#3]
It appears that you didn't list https://slimdx.org/download.php as a required dependency but the program will continue to crash without the x86 version installed. Not sure if you were trying to phase out dependency on this framework but it's still required somewhere.

**Comment by mouldyXD** [comment]
Thank You soooo much this fixed all my problems ;)

**Comment by fqlx** [comment]
Truthfully, I didn't realize this.  I assumed the compiled included the dependency.  I updated the readme.  Thanks!

**Comment by AlphaTJH** [comment]
Might want to mention that it specifically needs the x86 version, I tried the x64 first and it continues to crash. used the x86 and it's all fine now.
