### ISSUE TITLE
Flickering Triggers

### ISSUE THREAD

**Issue by zeekw** [fqlx/XboxKeyboardMouse#30]
When the triggers are set to a keyboard key, they can not be held down. Instead, the trigger flickers on and off rapidly.

**Comment by CallumCarmicheal** [comment]
This is a issue with the keyboard and mouse being called after one another, I was going to make it one or the other but this is a issue I currently know off and I am trying to find a solution for it. 

Here is the issue:

In the input thread, we take the keyboard input and then the mouse input. on the current build the mouse resets the trigger on each call without checking if the keyboard had turned on the trigger. As for right now this bug will have to stay until I can find a better way of stating that a key was pressed.

**Comment by DavidRieman** [comment]
I believe this is fixed - at least I haven't noticed it anymore in my branch.  Close?
