### ISSUE TITLE
Keyboard Not Working, Help?

### ISSUE THREAD

**Issue by KingOwnageXV** [fqlx/XboxKeyboardMouse#31]
The ScpToolKit messed up my keyboard, I accidentally selected the wrong thing and now my keyboard won't work at all. How do I fix my keyboard drivers so they can work again? Thank you for your help ahead of time

**Comment by KingOwnageXV** [comment]
Also what drivers am I suppose to install with ScpToolKit?

**Comment by CallumCarmicheal** [comment]
Besides ScpToolkit there should not be any other required drivers, at least that i am aware of. 

If you have any more issues please reopen this issue.
