### ISSUE TITLE
Everything is working except mouse movement

### ISSUE THREAD

**Issue by XDSS2002** [fqlx/XboxKeyboardMouse#32]
Every except the mouse movement works. In the XboxKeyboardController Program, the right stick doesn't work, as also it doesn't in the Xbox App either. I've tried both x32 and x64 versions. Can anyone help? Also the mouse shows while moving it in the xbox app

**Comment by CallumCarmicheal** [comment]
What do you mean the mouse does not work, Not moving at all or it is poor performance like segmented/pretty bad. If its pretty bad thats because i cant figure out a good way to translate mouse -> joystick. 

If it does not work please click "Controller" to open the controller preview tab and check what your sticks look like, please note you do not need to have the xbox app in fullscreen to do this!

**Comment by XDSS2002** [comment]
I have checked the app showing the controls and everything highlights when pressed, and the left stick works when pressing WASD. Also, left and right click works too. It's just the right stick movement that is not working.

**Comment by XDSS2002** [comment]
So basically it's not moving at all

**Comment by CallumCarmicheal** [comment]
Hmm, i am currently unable to attempt any fixes tonight due to not being in my house. I will be-able to attempt a fix tomorrow. If you are able please clone the source code and build the source and see if your problem persists.

**Comment by aviioc** [comment]
Hello, I just installed the program with all the prerequisites and just like Xdss everything works but the mouse control. The cursor isn't locked or anything and no right stick input comes through (I was using Xbox one streaming)

**Comment by fqlx** [comment]
Can you look at the history and try an older executable and see if it works?

**Comment by aviioc** [comment]
Really sorry, I'm fairly new to github and can't find any history or older downloads, do you have a link?

**Comment by CallumCarmicheal** [comment]
@aviioc could you please send the profile ini you are using so we could test this under the similar substances.

**Comment by mobiri** [comment]
i have the same issue, everything responds great including mouse clicks but mouse movement does nothing, just using the default ini with no changes

**Comment by CallumCarmicheal** [comment]
@mobiri when i get time, later tonight ill make a debug build that will print the inputs so we can debug this issue.

**Comment by xpjor1x** [comment]
Can confirm, have tried pretty much everything when it comes to this software and I can't get mouse input to work. 64 bit. Tried running as admin, running as non-admin, nothing works.

**Comment by CallumCarmicheal** [comment]
Could you please download this version of XKM and place it in the folder where you have stored the application and run it.

You will see a console window open up, ignore this for now.

Click settings and load your config as normal, you will now see a "Debug" tab - Please click it and then tick "Mouse Engine: Print SetAxis Values".

Now place the console window (text window) in a place where you can see it when you have the xbox app open (You can do this when the xbox app is not fullscreen or streaming the xbox).

Start the app using your ON/OFF key then click-inside the Xbox Application.

You will now see a bunch of numbers appearing in the console, start moving your mouse and confirm that they do not move at all.

[XboxKeyboardMouse_Debug_04.07.17.22-45.zip](https://github.com/fqlx/XboxKeyboardMouse/files/1123109/XboxKeyboardMouse_Debug_04.07.17.22-45.zip)

If you have no numbers when moving your mouse please goto the folder "profiles" and then attach your profile and then notify me using @ 

@XDSS2002 @aviioc @mobiri @xpjor1x

**Comment by mobiri** [comment]
i was able to get everything working, turns out my issue was that it didnt occur to me that i was using the xbox beta app instead of the xbox app and switching to the regular xbox app fixed everything up fine .  wish i had thought of it before lol if any of the other people are using the beta app they might wanna try using the regular one

**Comment by CallumCarmicheal** [comment]
Hmm, i did not think that would not be a issue, ill write a patch for it later tonight! Thanks for finding the issue and posting you're fix.

**Comment by Vinc0310** [comment]
[Preset 1.zip](https://githu@CallumCarmicheal .com/fqlx/XboxKeyboardMouse/files/4484333/Preset.1.zip)

**Comment by Vinc0310** [comment]
@CallumCarmicheal 


[Preset 1.zip](https://github.com/fqlx/XboxKeyboardMouse/files/4484337/Preset.1.zip)
