### ISSUE TITLE
Instant crashes

### ISSUE THREAD

**Issue by efsmert** [fqlx/XboxKeyboardMouse#37]
Whenever I start the program it says: XboxKeyboardMouse has stopped working. I have everything required installed to my machine and I don't know how to fix it.

**Comment by CallumCarmicheal** [comment]
Do you get any error messages at all?

**Comment by CJBritton** [comment]
Same happened to me, I have all the files installed yet it instantly crashes. Is there something that I am doing wrong?

**Comment by CallumCarmicheal** [comment]
What type of crash do you receive, is it: "Has stopped working", or some other type of crash. If it all possible could you please share a screenshot of this - so i may know what is going on.

**Comment by SubSonix** [comment]
Possibly unrelated, but may help others anyway.
I had crashes of the Xbox App due to my high refresh rate. The Xbox App doesn't like to run over 60 fps.
I limited mine down to that and no problems since. :)

**Comment by CJBritton** [comment]
No worries I found my problem. It kept saying that the program had stopped working on launch and then close it. I looked into the script and saw it was crashing on making sure a mouse was plugged in. For some reason It did not like my mouse. So I plugged in another one and it worked fine. Thank you :)

**Comment by CallumCarmicheal** [comment]
@CJBritton Could you tell us what mouse you were using? This could be a global compatibility issue.

**Comment by GaabrieeLp** [comment]
It happens to me when I try to open the x64 version, I solved it by installing [SlimDX](https://slimdx.org/download.php) x64 too instead of only the x86 version like described in the Prerequisites

**Comment by fqlx** [comment]
Don't forgot to add the missing DLLs
