### ISSUE TITLE
Tutorial Video? Better instructions

### ISSUE THREAD

**Issue by KingOwnageXV** [fqlx/XboxKeyboardMouse#39]
Can someone on here make a video on how to do all of this? I messed up my keyboard and mouse drivers for a week trying this and don't want to try it again unless there's a video tutorial, everything would be so much simpler and easy for everyone if someone on here could make it. Thank you ~ Ownage

**Comment by CallumCarmicheal** [comment]
I am very video awkward and have a very bad microphone, although tomorrow i will be getting a new microphone and posting a update.

I will make a tutorial video tomorrow, (Just gotta setup a VM so i can start from scratch).

**Comment by KingOwnageXV** [comment]
Thank you, sounds great! :) just make sure to link me to the video once it's up if you can

**Comment by KingOwnageXV** [comment]
Let me just say it's completely okay if you're busy at the moment or changed your mind about doing it, not rushing just wondering if you're still planning on making the video because you said tomorrow and it's been 5 days since you said that

**Comment by CallumCarmicheal** [comment]
@KingOwnageXV I've been having problems with the VM, I finally got it working a hour ago. The video should be up very soon, i have also been very busy. I am so sorry about this. Should not be long now.

**Comment by KingOwnageXV** [comment]
Just another question where was it uploaded to? I'd like a link of possible I can't find it on github, if you even can upload videos to GitHub I don't really use it that much

**Comment by CallumCarmicheal** [comment]
@KingOwnageXV I will have it uploaded by the 28th (sorry this has literally taken more than a few weeks), i've been ploughing through work at the moment.

**Comment by theguywhoyousaw** [comment]
I can do the video if you'd like, currently setting up the program to start with

**Comment by KingOwnageXV** [comment]
That would be nice of you, but if anyone of you do the video can you comment a link so I know where it's at

**Comment by CallumCarmicheal** [comment]
@KingOwnageXV I tried to make a tutorial video but while doing that i realised i am the most video awkward person in existance and i honestly suck at After Effects. So if @theguywhoyousaw could make the installation video that would be awesome, if not ill just attempt to crawl out of my cave and give it another shot. I am very sorry ;(

**Comment by fqlx** [comment]
There's some YouTube videos now.
