### ISSUE TITLE
Mouse buttons work. Mouse movement does not.

### ISSUE THREAD

**Issue by LouisWhit** [fqlx/XboxKeyboardMouse#4]
Any idea on how I troubleshoot this? Both mouse buttons work correctly... The game (overwatch) gets absolutely none of my mouse movements. All keyboard items seem to function correctly.

**Comment by fqlx** [comment]
Does the mouse cursor disappear? Do you have two monitors? Install Slimdx runtime?

**Comment by fqlx** [comment]
Try running it full screen? Check the TranslateMouse.cs

**Comment by LouisWhit** [comment]
I have 3 monitors. I am running the xbox app on the primary monitor. It is full screen. The mouse cursor goes away when playing the game. The keyboard and mouse application says running in green.

**Comment by LouisWhit** [comment]
I just noticed.. if I move the mouse extreeeeeeeemly slowly. It slightly moves the view by a few pixels in the direction I am moving the mouse. Does the dpi settings of the mouse make a difference?

**Comment by LouisWhit** [comment]
@fqlx Per slimdx... I installed the x64 for .net 4.0 originally. I was having an instacrash. I read the other messages on here and that helped me find that I needed the x86 runtime installed. So I installed the x86. That got me to here. Everything but the mouse direction inputs are working flawlessly. Fast mouse movements don't register at all. Extreeeemly slow micro mouse movements register in the slightest degree. I would say that a slow full slide across my mousepad results in a movement of 10-20 pixels in that direction. In my mind the input is being detected by the software. Something in my setup/settings must be causing an issue. I would be happy to join.me or gtm with you if needed. I am using a cheap AZZA Alpha mouse ( https://www.amazon.com/AZZA-Gaming-Mouse-USB-Pc/dp/B00CCJ08KE ) The mouses uses whatever default drivers microsoft installed when I plugged it in. I have used it for 2 years with no issues on anything else.

I'll test anything you throw at me. Thank you for ideas and help.

**Comment by fqlx** [comment]
I'm suspecting it has to frame_per_tick being too small or your CPU is super fast or your CPU doesn't support "a high resolution performance counter" (https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.frequency(v=vs.110).asp). The variable is how much time we need to wait before getting the next mouse position. There isn't really a great way to do this. If you have VS installed, try modifying the tick count. I'll try to update it later this week to let the user set their own tick count (sensitivity) in the app.

**Comment by LouisWhit** [comment]
I am a front end web developer. I use a lot of sublime. I have never used VS before. I can mess with it. I have no clue how to do builds etc.

My processor is an AMD FX 8320 Eight Core 3.5ghz   If that helps.  

Do you think I should be increasing or decreasing my tick count?

**Comment by ITomPark** [comment]
this is the time when I regret not having VS , are the tick count values on the TranslateMouse.cs right?.

**Comment by fqlx** [comment]
This line of code:
`                double frame_per_tick = FRAME_PER_60FPS_IN_MS * nanosecPerTick - ESTIMATED_LOOP_COMPLETION;
`

**Comment by fqlx** [comment]
I updated the app to allow custom tick count.  Give it a try.
