### ISSUE TITLE
Mouse is unresponsive

### ISSUE THREAD

**Issue by kiseylips** [fqlx/XboxKeyboardMouse#40]
I have all of the applications needed to use my mouse and keyboard, and it works. But, with the mouse, it will move, but it needs to be moved about half an inch before it starts moving in game, this makes it very hard to coordinate the game movement with the mouse moves. I'm guessing this has to do somewhat with the sensitivity and tickrate, but I don't know what changes to make.

**Comment by CallumCarmicheal** [comment]
@kiseylips The mouse system we are using is very bad, i am still unable to think/make up a better system, i am still unable to find a effective way of mapping a mouse to a joystick x y axis - something which sounds easy but is hard to do in practice. I am very sorry for this inconvenience, you have to just keep tinkering with it to try and find a sweetspot for yourself.

**Comment by CallumCarmicheal** [comment]
I can assume that you was using the Xbox Beta app, if this is not the case please reopen this issue!

**Comment by mazh91** [comment]
Why are you guys mapping the mouse to the XY axis, instead of the 4/5 axis? It seems that you're making the controls more complicated that they should be.
