### ISSUE TITLE
Mouse movement isn't working

### ISSUE THREAD

**Issue by DarthCourteous** [fqlx/XboxKeyboardMouse#43]
No matter how many settings I mess with I can't get the mouse movement recognized. The keyboard works, the mouse buttons work, but moving the mouse to move the virtual right stick doesn't. It does make the mouse cursor appear and bring up the little menu bar that lets me mute the mic or stop streaming, but nothing in game happens when I move the mouse

**Comment by CallumCarmicheal** [comment]
This is a strange issue that everyone seems to be having except me, could you possibly upload the exe you are using, the XboxKeyboardMouse exe. That will allow me to see if it's just a glitch or the code for the house handler was commented out to check from bugs/mistakes without realising it.

**Comment by GameInGameOut** [comment]
I had issues with this as well, I got it to work now though, try these:

1. Make sure you are using the Xbox app (not Xbox beta)
2. Set the mouse mode thing to raw + sensitivity. Sorry, I'm away I can't give you the config I got working
3. Log into your account on the Xbox, and then disconnect ALL controllers from your Xbox.
4. If the mouse feels strange,  go into the games controller settings and, in the case of Overwatch, change the controller mode off dual zone or whatever its on an change it to linear graph

**Comment by DarthCourteous** [comment]
thanks for responding so fast!! I was using the beta app. The regular xbox
app does work (with Halo 5 at least). The cursor stays on screen but I can
live with that, it feels like once I tweak the sensitivity it'll work
great. What a great app, thanks again for your help. I can still upload
exe's if you want, just let me know, but once I switched away from the beta
app everything started working

**Comment by CallumCarmicheal** [comment]
@DarthCourteous There is no need to upload the executables, ill have a update being released very soon to add support for the Xbox Beta application, this seems to be a recurring issue ;)
