### ISSUE TITLE
possible to use with ps4 remote play ? 

### ISSUE THREAD

**Issue by excision1** [fqlx/XboxKeyboardMouse#46]

**Comment by CallumCarmicheal** [comment]
If the remote play application works with a Xbox controller then with a few changes to the source code this may work, ill test it tomorrow when I have time right now I'm trying to see if I can get the mouse to work nicely.

**Comment by fqlx** [comment]
SCP driver supports PS4 control so it could work.  I think we'd need to add the stream to look for PS4 remote play applicatioin too.

**Comment by fqlx** [comment]
I think this could work but I don't own a PS4 or have any help

**Comment by internet-corey** [comment]
I cloned the repo and added "PS4 Remote Play" to the defaultAppNames string array in XboxStream.cs and then ran a build.

The app recognizes when PS4 Remote Play turns on (app goes green), but the buttons don't do anything. They are registering if you click on the Controller Live/Realtime Preview, but they don't do anything in the Remote Play app.

**Comment by fqlx** [comment]
I think that could work with a Xbox controller
