### ISSUE TITLE
Mouse movement doesn't work

### ISSUE THREAD

**Issue by HuhllucinatioN** [fqlx/XboxKeyboardMouse#47]
my mouse movement doesn't register as Right Stick, instead it keeps bringing up the streaming overlay bar, other inputs are all working as intended

**Comment by CallumCarmicheal** [comment]
Are you using the beta xbox app?

**Comment by CallumCarmicheal** [comment]
No response received in 25 days, if you or anyone else still receive this issue please reopen this issue.
