### ISSUE TITLE
Edit Keys

### ISSUE THREAD

**Issue by slygy** [fqlx/XboxKeyboardMouse#48]
i want to edit what keys activate what buttons on the controlling but i cant figure out how. how do i do this?

**Comment by CallumCarmicheal** [comment]
When opening the application you will see a Blue background with a on button, look under that to see a controller icon and a settings icon.

Click the controller icon then click "Preset Name" in the bottom corner above "Add Preset". Type in the name of the game you will be playing and click "Add Preset".

Click the game name and then press "Load Preset" in the bottom left.

Click the "Keyboard" tab and then hover over the button you want to edit, move the mouse around near it until the key turns green, double click and it should appear with a new window that says "Select key for - ..." Press any key while inside this window and you should see it show up in the preview text.

When you are finished selecting the key you want press "Okay - Select key". Go back to the settings tab and then press "Save All Changes".

Go back to the "FILE" tab and find the text that says "Active Preset" if the preset does not say the same as "Editing" select the preset in the list of games and click "Set as Active" now the preset you just added and configured should be selected and saved.

--------------

To play a game with this preset press the On/Off key defined in the "Settings" tab to turn off the xbox controller (parts of the window should turn red to show that its disabled) and then open the Xbox App (Not the beta app, this will be receiving support soon).

Select your xbox and start streaming, press the On/Off key to turn it back on while in the xbox streaming overlay and you should now be-able to use the virtual xbox controller to control your xbox one.

--------------

Anymore questions relating to editing keys please reopen this issue if not but you have another question not related to this please open another issue :)
