### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by Ghoron23** [fqlx/XboxKeyboardMouse#5]
started using the most recent .exe and noticed that the tab key/back button weren't working.

**Comment by fqlx** [comment]
Do you know if this was working before?  The last build and newest don't work for me.

**Comment by Ghoron23** [comment]
It thought It worked on the last one. I still have the zip folder from the last one so I'll check on that tonight.

**Comment by fqlx** [comment]
I don't remember it ever worked, haha.  I took a look at the code and this problem might be fairly difficult to fix.

**Comment by Ghoron23** [comment]
just tried the last build and I can confirm it doesn't work there either.

**Comment by fqlx** [comment]
Fixed it and I switched the back button to 'B' instead of Tab as a workaround for another issue.
