### ISSUE TITLE
Can you make a tutorial video? i cant seem to get this to work.

### ISSUE THREAD

**Issue by RXPxBoltz** [fqlx/XboxKeyboardMouse#50]
i would appriciate if u did so, i always get loads of errors thanks

**Comment by CallumCarmicheal** [comment]
Could you elaborate what type of errors, im kinda camera shy fixing the issue is better than a video 🐱

**Comment by ditzypuff** [comment]
Hi, same here. I've installed all of the prerequisites and followed instructions but the Xbox App won't take inputs

**Comment by CallumCarmicheal** [comment]
@ditzypuff does the mouse get locked ? And when u press controller preview do u see any buttons lighting up?

**Comment by ditzypuff** [comment]
I don't know how but it started working minutes after I posted that. I think it just wasn't hooking into the app properly? I don't know..
The inputs did light up in the controller preview.

**Comment by fqlx** [comment]
There's videos on YouTube.
