### ISSUE TITLE
My problem with xbox app

### ISSUE THREAD

**Issue by FreeXKill** [fqlx/XboxKeyboardMouse#56]
After a while of attempting, il finally found why my ScpVBus was outdated. I simply manually updated it. And now! The program is working pretty well! But in the xbox stream, with the cursor stuck at the middle of the screen. No key are working on the app. Is it my virtual controller or something else ? 
Thanks for replying soon!

**Comment by CallumCarmicheal** [comment]
Does the application turn green when you are inside the xbox app?

**Comment by FreeXKill** [comment]
Yes it is, and when I'm doing alt-tab, it's turns blue. The program works perfectly fine. But I think it's the virtual controller the problem. What do you think about that?

**Comment by CallumCarmicheal** [comment]
@FreeXKill blue means standby, red is off and green is on. Does the app turn green when you go inside the app, it needs to be the Original Xbox App not the beta

**Comment by FreeXKill** [comment]
I have to repair my pc, I'll by able to try in 3 or 4 days. I got a screw in my laptop's fan. Don't even imagine how it's frustrating xD I'll reply in few days :)
