### ISSUE TITLE
when I open xboxkeyboard app it says stopped working and it closes. I downloaded the other two things and it closes

### ISSUE THREAD

**Issue by hlavabr13** [fqlx/XboxKeyboardMouse#57]

**Comment by FreeXKill** [comment]
Hi, I got the same problem as you before, can you tell me something? Go on your pilotes and tell me if ScpVBus seems to be "outdated".

If yes, just install ScpVBus (x64 or x86) and update the pilotes by yourself.
Heres the link:
https://github.com/shauleiz/vXboxInterface/releases

I hope that I helped you :)

**Comment by FreeXKill** [comment]
I meant drivers instead of pilotes sorry. I'm just saying that because some person would be confused.
