### ISSUE TITLE
Data.cs serialization

### ISSUE THREAD

**Issue by DavidRieman** [fqlx/XboxKeyboardMouse#60]
I'm wondering if there's a reason Data.cs uses a verbose .ini read/write tactic.  This could be a fraction of the code via XML serialization.  With the members named the way they are, it seems the same human-readable information would be present.

**Comment by DavidRieman** [comment]
Basically, would it be a welcome change if I found time to simplify it to XML serialization?

**Comment by CallumCarmicheal** [comment]
I have never used XML in c# before only json.net but Jason.net has licenses n stuff so I improvised, it's a bitch to maintain but It works for it's purpose. It can be easily modified to make it serializable but besides that there is no other reason.

**Comment by CallumCarmicheal** [comment]
If you would like to go ahead and move it to XML I'm sure it would be a welcomed change just leave the reading code in as a legacy backup so if users had old configs we can read them in and convert them maybe?

**Comment by DavidRieman** [comment]
Started going down that path, but backed out the changes.  Serializing Data with XmlSerializer was trivial, but back-supporting two file types was getting a little hairy.  Committing the other crash fix and code cleanup though.
