### ISSUE TITLE
issues and crashing

### ISSUE THREAD

**Issue by tunip3** [fqlx/XboxKeyboardMouse#64]
when attempting to use it i get the error

System.IO.FileNotFoundException: 'Could not load file or assembly 'SlimDX, Version=4.0.13.43, Culture=neutral, PublicKeyToken=b1b0c32fd1ffe4f9' or one of its dependencies. The system cannot find the file specified.'

**Comment by CallumCarmicheal** [comment]
You need to install the SlimDX library, please check the prerequisites. https://github.com/fqlx/XboxKeyboardMouse#prerequisites
