### ISSUE TITLE
Doesn't work for games?

### ISSUE THREAD

**Issue by EPICcake808** [fqlx/XboxKeyboardMouse#7]
I think that is an excellent idea. The only thing is that it doesn't work for games. (Please excuse me, I'm a noob at all this stuff) Is it supposed to work for games as well? Or is it only for the home screen?

**Comment by fqlx** [comment]
It works for games. Make sure it's the first button you click when you load the game. That locks the controller.
E.g. the start button in Halo

**Comment by EPICcake808** [comment]
Oh, so I can't have the game running on the Xbox first, and then load up the game's main menu? I have to start up the game while streaming?

**Comment by MattMistele** [comment]
Think of this program as another Xbox controller. It creates a virtual controller on your computer, but to your Xbox, this 'looks' like just another controller. If your Xbox has another controller already connected, this program would be "controller #2" on your Xbox. You can control anything on your Xbox with this.

For your problem, it seems as you start a game with another controller, then start to use this program to control the game. Try quitting out of the game, then launching the game with this controller - that way the game recognizes this program as your "main" controller, not controller #2 when it was looking to be played with controller #1.

**Comment by EPICcake808** [comment]
Oh that makes so much sense! Thanks. I'll try this at home. Hopefully it works! :)

**Comment by MattMistele** [comment]
Awesome :)
