### ISSUE TITLE
How does the Mouse sensitivity work?

### ISSUE THREAD

**Issue by whatdehek18** [fqlx/XboxKeyboardMouse#70]
Can I get an explanation on how the to change the sensitivity in the settings? I'm confused on how to make it more or less sensitive.

**Comment by jsgrissom88** [comment]
First of all turn the sensitivity all the way up in your game settings.
Then on your PC open your mouse properties and adjust the speed under
pointer options to your liking. Just tinker with the dpi settings until you
find a sensitivity you're comfortable with.

**Comment by whatdehek18** [comment]
Gotcha. Does it help with the lag?

**Comment by Spazual** [comment]
I left the defaults for the x/y axis, but the mouse circles around like crazy, and the cursor stays even if it's unchecked. Am I running it wrong?

**Comment by DavidRieman** [comment]
I'll clarify that you don't have to change the actual mouse driver pointer speed or anything.  The higher the mouse X/Y sensitivity values in the XboxKeyboardMouse Settings -> Mouse area, the less you have to move the mouse to reach maximum simulated stick tilt, so the sensitivity is adjustable that way without messing with your normal mouse settings.

The lag issue, depending on what you meant, may have been solved with the version in the new ClickOnce installer and the dead-zone-handling mouse engine.  If not, please let us know.

**Comment by DavidRieman** [comment]
Closing; we should document this via #102
