### ISSUE TITLE
Axis Sticks are getting stuck if both at pressed at the same time (Love it)

### ISSUE THREAD

**Issue by Otffaeva** [fqlx/XboxKeyboardMouse#71]
Thanks for making this program it works perfect on my pc when streaming xbox one games lik madden 18 Nba 2k18 only problem I have is on games lik gears of war n call of duty where the right axis will get stuck if it's pressed at the same time the left axis is pressed is there any way to fix this..Thanks in advance cuz I'm sure there's a way lol

**Comment by CallumCarmicheal** [comment]
@Otffaeva Would it be possible for you record or give a image that demonstrates the issue of the sticks getting stuck / jamming.

**Comment by Otffaeva** [comment]
Can u tell me how am I suppose to do that please

**Comment by CallumCarmicheal** [comment]
@Otffaeva if at all possible you could record your screen via OBS and upload it to youtube.

**Comment by Otffaeva** [comment]
https://cl.ly/470p1b2N2R3W

**Comment by Otffaeva** [comment]
its showing kinda fast but as u can see when im moving and i try to look around with the right axis it gets stuck whenever im pressing the left axis then press the right axis the right axis will get stuck..it only creates problems in games lik gears of war and call of duty

**Comment by Otffaeva** [comment]
i tryd recording and uploadimg to youtube but the recorder i normally use isnt working so i resorted to doing it with another recorder...

**Comment by DavidRieman** [comment]
The axis handling got refactored a bit a while ago and may well have fixed this bug.  Let us know if you still have issues with a newer version of XboxKeyboardMouse.

**Comment by DavidRieman** [comment]
A new version is available via the home page installer link.  Closing this stale issue, but let us know if you still have issues with it.
