### ISSUE TITLE
Mouse movement not work

### ISSUE THREAD

**Issue by bangclaude** [fqlx/XboxKeyboardMouse#72]
Hi
It looks like everything except the mouse movement (right stick) does not work. It is in the streaming app only a slight shake up.
What can it be, how can it be fixed?
If necessary, I can also record a video or stand for a Skype transfer available.

**Comment by fqlx** [comment]
Hey, I haven't used the app in a while and a ton of people have reported this issue. If you could send me a video I'll fix it.

**Comment by eddamoo** [comment]
I've just downloaded the package and encountered the same issue on both a Dev VM and my local machine.

When loading the "Game Controllers" input viewer in windows, all keyboard inputs work fine, but mouse inputs are not transposed.  Strangely, when you click within that window and leftmousedown, the Z-Axis goes to 0.  When you rightmousedown, the Z-Axis goes to max.

Happy to fire a team-viewer over to the Dev VM if you fancy looking?

**Comment by eddamoo** [comment]
OK, didnt take long but i got it to work.  Turns out testing it in windows is useless and after going straight to the XBOX streaming app, it works beautifully.

Thanks for all your efforts :)

**Comment by fqlx** [comment]
It waits for the Xbox streaming app to be in the foreground  Is that why it works now?

**Comment by eddamoo** [comment]
Yeah exactly - i went digging into the code and that's exactly what i found.  I strongly suspect that other people who have this issue are doing the same (seeing if it works in windows first).

It may be worth stating on your main page that it only works with the Xbox app and the button goes green when enabled, as in other applications (lets say Rocket League on the PC), all buttons work except for the mouse axes!

Thanks again for the great app :)

**Comment by fqlx** [comment]
Ah good idea about adding a note to the main page.  Glad you got it working 🙂
