### ISSUE TITLE
Fortnite settings

### ISSUE THREAD

**Issue by shamwow609** [fqlx/XboxKeyboardMouse#73]
Hi. When I play Fortnite Battle Royale using the XboxKeyboardMouse executable, the mouse movement gets too "stringy", and if I rebind the keyboard controls to something else in-program, I end up not being able to move (but can do things like open parachute, open map, etc.) I guess what I'm asking is, "does anyone have a profile for Fortnite". Thanks in advance.

**Comment by Spazual** [comment]
I was looking for the same thing, I can't get ride of the cursor and can't seem to get the settings right. In either the mouse or program

**Comment by fyre99** [comment]
Same here

**Comment by RichardRoot** [comment]
same and is there any other way of doing this,Cause I really want to use my keyboard and mouse but this is really inaccurate and I dont want to buy stuff to play with keyboard and mouse any other ways?

**Comment by SubSonix** [comment]
I don't want to point out the obvious, buy why not just play it completely on PC?

**Comment by shamwow609** [comment]
Well, more people I know are on console, making squads more "fun".

**Comment by LTsnazzy** [comment]
you can link your Xbox account to pc so you can join friends on Xbox while you are on pc but they cant join you're lobby you can only join theirs.

**Comment by SubSonix** [comment]
@shamwow609 Fair enough :)
@LTsnazzy Even better, didn't know you could do that

**Comment by fyre99** [comment]
@LTsnazzy This method gives the error "Your account can't play on this platform"

**Comment by LTsnazzy** [comment]
you got to log in to your account first on the site and press link accounts
https://accounts.epicgames.com/linkMsId?productName=fortnite&successRedirect=https%253A%252F%252Fwww.epicgames.com%252Ffortnite%252F&lang=en_US

**Comment by LTsnazzy** [comment]
here is a video if you want some extra details.
 https://www.youtube.com/watch?v=1kr2vQlOGkw

**Comment by shamwow609** [comment]
@LTsnazzy You sure it still works? I tried, and couldn't get it to work. The creator of the video also said "This now only works between PC and PS4 as Xbox has removed all cross compatibility. If you are on Xbox this will no longer work for you, but if you are on PS4 this still works!"

**Comment by shamwow609** [comment]
(when I tried to link it said it was already linked to another acccount)

**Comment by LTsnazzy** [comment]
sorry to hear that I play on ps4 with friends but have an Xbox one to saying the same I just assumed it was because I liked it to my Xbox epic games account. Hope Xbox will fit it

**Comment by ctal96** [comment]
How do you get mouse movement as right analogue stick?

**Comment by DavidRieman** [comment]
#125 covers that we need to investigate getting XKM to work well with Fortnite.  Closing this issue.
