### ISSUE TITLE
High CPU usage?

### ISSUE THREAD

**Issue by gonespy** [fqlx/XboxKeyboardMouse#74]
The 64-bit program constantly uses ~30% CPU. I tried using None for the mouse engine but it's still like that.

Is this normal? The only reason I'm raising the issue is because streaming to my Xbox One keeps stopping due to "Network quality problems" (even though both PC and XB1 are on the same wired network) - I thought it might be related - too much CPU means the app can't decode the stream fast enough or something

**Comment by KibroIsKawaii** [comment]
Your CPU ?

**Comment by gonespy** [comment]
i5-3570K

**Comment by DavidRieman** [comment]
There used to be very aggressive looping that would peg a CPU.  Please see if a new version (especially my new one at https://github.com/fqlx/XboxKeyboardMouse/pull/83) has since resolved this.
