### ISSUE TITLE
scp bus 

### ISSUE THREAD

**Issue by p4zk** [fqlx/XboxKeyboardMouse#76]
when i run xboxmouseleykeyboard it say scp bus failed to initialise

**Comment by BesiHyseni** [comment]
i got the same problem

**Comment by CallumCarmicheal** [comment]
[You need SlimDX Runtime installed (x86)](https://slimdx.org/download.php)

Could you check if you have that installed by going through your Control Panel?

**Comment by LilCrispy2o9** [comment]
Everything installed... still a no go

**Comment by Beef-Curry** [comment]
Same issue! When I run "XboxKeyboardMouse 24 02 2017 - x86_64" I receive the same error and after I click 'ok' I receive this:

![image](https://user-images.githubusercontent.com/37779510/37878391-9d64d26a-3060-11e8-9a24-5f733688b513.png)

Any help would be greatly appreciated!

**Comment by Beef-Curry** [comment]
This worked for me: https://github.com/fqlx/XboxKeyboardMouse/issues/52

You have to install ScpToolkit and go into ScpToolkit Monitor (Legacy) and click install. I recommend uninstalling after you're done playing, but make sure the XboxKeyboardMouse program is closed first, because when it wasn't my computer completely crashed.

**Comment by DavidRieman** [comment]
The last time I had issues with this, it was before I got the ScpVBus installer and device sim to behave better.  Basically the mock controller devices had accumulated in the Device Manager.  Resolving was a matter of unplugging any physical 360 peripherals (if any), opening Device Manager, deleting all of the "Xbox 360 Peripherals" entries, and trying again.

**Comment by DavidRieman** [comment]
Closing; We should document this better with #102
