### ISSUE TITLE
Remove the Downloads folder and Move to Github Releases

### ISSUE THREAD

**Issue by CallumCarmicheal** [fqlx/XboxKeyboardMouse#78]
Rather than using the downloads folder, i think a better solution would be to make sure of the Github's Releases page. This has the added benefit of archiving the source code for the given Executable. What do you think @fqlx ?

**Comment by fqlx** [comment]
Absolutely a great idea!

**Comment by CallumCarmicheal** [comment]
Wrong issue *my bad*
