### ISSUE TITLE
Any way to map other keyboard keys?

### ISSUE THREAD

**Issue by martchoice** [fqlx/XboxKeyboardMouse#79]
How does it work to map different keyboard keys?

**Comment by DavidRieman** [comment]
Ok, so I finally took the time to investigate how this key customization part of the app works.  LOL.

Currently, here's how you do this:
* First, select Settings, and ensure there is an "editing" profile.  In the latest version available, via the new home page linked installer, there is automatically an "editing" profile.
* Click the "Keyboard" tab.
* Double-click the part of the controller you want to change a key for, such as the Right Bumper area (which may be showing the default-mapped "E" key over it).  A dialog opens.
* In this dialog, press a key on the keyboard that you want to map to it.  E.G. you press "T"
* Select "Okay - Select Key".  E.G. now the keyboard "T" key will map to "Right Bumper".
* Select "Settings" tab.
* Select "Save All Changes".

**Comment by michael-ts** [comment]
@DavidRieman  Is it possible to map each key to itself?  e.g. to use the keyboard in a chat window sort of thing.

**Comment by DavidRieman** [comment]
Unmapped keys pass straight through, so if you dont want to map keyboard keys to controller inputs then you can unmap them from a profile.  Also note the key combo to toggle -- alt+C if I recall -- though I logged a bug where that alt press can screw things up as it also translates. See if it suits your needs though?

**Comment by DavidRieman** [comment]
Closing; we should document this stuff better with #102
