### ISSUE TITLE
Mouse movements are coarse in Halo 5

### ISSUE THREAD

**Issue by Lmx154** [fqlx/XboxKeyboardMouse#81]
I've tried messing with the settings a bit, but I haven't been able to get rid of the coarse aim. By coarse I mean the mouse sticks to where I aim and I have to jerk it away so it will move smoothly again which makes it impossible to aim accurately. Everything besides precision aiming works very well though. Does anyone have any advise or maybe a preset to fix this?

**Comment by fqlx** [comment]
Try the deadzone code
