### ISSUE TITLE
Can't Find 64 Bit Build

### ISSUE THREAD

**Issue by OmegaAlphaDuderino** [fqlx/XboxKeyboardMouse#87]
I'm having a bit of trouble finding the 64 bit build, Apparently I'm downloading the 32 Bit build since my mouse isn't disappearing and when I press escape my stream shuts off.

**Comment by fqlx** [comment]
Any CPU was causing problems.  I uploaded the x64 bin.  I'm not uploading the x86 bin unless people really want it.
