### ISSUE TITLE
Option to disable the need to use the Xbox streaming app

### ISSUE THREAD

**Issue by brunibunny** [fqlx/XboxKeyboardMouse#95]
There are some cases where this would come in handy. For exemple: The PC port of Resident Evil: Revelations 2 has local splitscreen co-op, but only if both players use gamepads. The game ignores mouse input completely when this mode is active. Having the option to disable the foreground app check and the mouse lock/hide functions would be tremendous.

**Comment by CallumCarmicheal** [comment]
Should not be that hard, I'll create a option when I get up, as for now if you would like you can disable it your self in 

https://github.com/fqlx/XboxKeyboardMouse/blob/84f6da191a96a08abb21d2d658835c3034eff3c6/XboxKeyboardMouse/XboxController/Emulation/XboxStream.cs

**Comment by brunibunny** [comment]
Awesome. Thank you!

**Comment by brunibunny** [comment]
It works perfectly with RE R2! I've also tried with GTA V, since it accepts both controller and keyboard at the same time. Working perfectly there as well.
