### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MungaFN** [fqlx/XboxKeyboardMouse#98]
Mouse is very glitchy and y axis is very slow. Can I change this?

**Comment by fqlx** [comment]
I've noticed diagonal movements are slower left to right than right to left.  Do you see this?

**Comment by MungaFN** [comment]
Yes, I thought maybe it was because my in game settings for the different axis but it wasn't. Also, will having a mouse acceleration fix cause the jumps in aim distance and non registered mouse movement I see?

**Comment by DavidRieman** [comment]
"having a mouse acceleration fix" - do you mean you have special driver settings that change how much the mouse moves over time or something?

**Comment by DavidRieman** [comment]
Hopefully the issues you were having were the aiming bugs that were fixed in the latest release, available via setup installer, linked on the home page readme.  Let us know if you still have any trouble with the new version.  Closing issue.
