### ISSUE TITLE
Immediatlely crashes, no report as to why.

### ISSUE THREAD

**Issue by calinzier** [fqlx/XboxKeyboardMouse#99]
Ive installed all prerequisites. Restarted my pc, and on initial launch it says "setting up xbox 360 controller". then it crashed and does so every time i try to run it.

**Comment by DavidRieman** [comment]
Try the troubleshooting steps listed at https://github.com/fqlx/XboxKeyboardMouse/issues/76 and let us know if that resolves

**Comment by DavidRieman** [comment]
Try out the new installer via the home page readme, and report back if you still have issues.  Closing issue for now.
